name: updateVpub
on:  
  push
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: update vpub
        shell: bash
        run: |
          pwd
          cd /
          pwd
          touch trial.sh
      - name: commit
        run: |
          git config --global heyu330182@hotmail.com
          git config --global user.name heyu330182
          git add .
          git commit -m "update:`date`"
          git pull --rebase
      - name: Push changes
        uses: actions/checkout@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
      
      
      
      
