name: updateVpub
on:  
  schedule:
    - cron: '30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: update vpub
        run: |
          sh trial.sh
      - name: commit
        run: |
          git config --global heyu330182@hotmail.com
          git config --global user.name heyu330182
          git add .
          git commit -m "update:`date`"
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      
      
      
